name: Run examples

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  
jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install packages
      run: bash build_tools/build_source.sh
    - name: Run Jupyter notebooks
      run: bash build_tools/build_examples.sh